import type { Metadata } from "next";
import { Victor_Mono as FontSans } from "next/font/google";
import "./globals.css";
import "./styles.css";
import "@coinbase/onchainkit/styles.css";
import { cookieToInitialState } from "wagmi";
import getConfig from "next/config";
import { Providers } from "@/components/providers/onchainkit";
import { headers } from "next/headers";
import Wrapper from "@/components/wrapper";

const victor_mono = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const h = await headers();
  const initialState = cookieToInitialState(getConfig(), h.get("cookie"));
  return (
    <html lang="en" className="dark bg-bg-white-0">
      <body className={`${victor_mono.variable} font-sans antialiased`}>
        <Providers initialState={initialState!}>
          <Wrapper>{children}</Wrapper>
        </Providers>
      </body>
    </html>
  );
}
